CREATE TABLE folders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE urls ADD COLUMN folder_id BIGINT DEFAULT NULL;
ALTER TABLE urls ADD CONSTRAINT fk_url_folder FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE SET NULL;
